version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      prisma:
        patterns:
          - "@prisma/*"
          - "prisma"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
      auth:
        patterns:
          - "next-auth"
          - "@auth/*"
    ignore:
      - dependency-name: "next-auth"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
